# Classifying Penguins with Keras

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

/Users/shanewaldron/Desktop/MSBA/GSB 545/In-Class Assignments/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [11]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

Requirement already satisfied: palmerpenguins in ./.venv/lib/python3.9/site-packages (0.1.6)
Requirement already satisfied: numpy in ./.venv/lib/python3.9/site-packages (from palmerpenguins) (2.0.2)
Requirement already satisfied: pandas in ./.venv/lib/python3.9/site-packages (from palmerpenguins) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/shanewaldron/Desktop/MSBA/GSB 545/In-Class Assignments/.venv/bin/python3 -m pip install --upgrade pip' command.

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [35]:
# drop Nan rows
penguins = penguins.dropna()
penguins.shape

(333, 8)

In [36]:
# shuffle the data
penguins = penguins.sample(frac=1, random_state=42).reset_index(drop=True)

In [37]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3250.0,39.5,16.7,178.0,True,False
1,3675.0,50.9,17.9,196.0,True,False
2,4000.0,42.1,19.1,195.0,False,True
3,4850.0,46.6,14.2,210.0,True,False
4,4050.0,41.1,18.2,192.0,False,True
...,...,...,...,...,...,...
328,4750.0,49.6,15.0,216.0,False,True
329,3900.0,37.2,19.4,184.0,False,True
330,3200.0,39.7,17.7,193.0,True,False
331,3950.0,45.2,17.8,198.0,True,False
332,3175.0,38.1,17.0,181.0,True,False

In [38]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.152778,0.269091,0.428571,0.101695,1.0,0.0
1,0.270833,0.683636,0.571429,0.406780,1.0,0.0
2,0.361111,0.363636,0.714286,0.389831,0.0,1.0
3,0.597222,0.527273,0.130952,0.644068,1.0,0.0
4,0.375000,0.327273,0.607143,0.338983,0.0,1.0
...,...,...,...,...,...,...
328,0.569444,0.636364,0.226190,0.745763,0.0,1.0
329,0.333333,0.185455,0.750000,0.203390,0.0,1.0
330,0.138889,0.276364,0.547619,0.355932,1.0,0.0
331,0.347222,0.476364,0.559524,0.440678,1.0,0.0
332,0.131944,0.218182,0.464286,0.152542,1.0,0.0

In [39]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)

In [40]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [41]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [44]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

/Users/shanewaldron/Desktop/MSBA/GSB 545/In-Class Assignments/.venv/lib/python3.9/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9527 - loss: 0.1750 - val_accuracy: 1.0000 - val_loss: 0.1296
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9553 - loss: 0.1498 - val_accuracy: 1.0000 - val_loss: 0.1263
Epoch 3/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9375 - loss: 0.1424

/Users/shanewaldron/Desktop/MSBA/GSB 545/In-Class Assignments/.venv/lib/python3.9/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9477 - loss: 0.1535 - val_accuracy: 1.0000 - val_loss: 0.1233
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9581 - loss: 0.1460 - val_accuracy: 0.9706 - val_loss: 0.1211
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9382 - loss: 0.1680 - val_accuracy: 1.0000 - val_loss: 0.1178
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9640 - loss: 0.1332 - val_accuracy: 1.0000 - val_loss: 0.1163
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9633 - loss: 0.1397 - val_accuracy: 1.0000 - val_loss: 0.1138
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9614 - loss: 0.1400 - val_accuracy: 1.0000 - val_loss: 0.1126
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9490 - loss: 0.1408 - val_accuracy: 1.0000 - val_loss: 0.1096
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9510 - loss: 0.1389 - val_accuracy: 1.0000 - val_loss: 0.1090
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9482 - loss: 0.1481 - val_accuracy: 1.0000 - val_loss: 0.1056
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9525 - loss: 0.1440 - val_accuracy: 1.0000 - val_loss: 0.1042
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9431 - loss: 0.1410 - val_accuracy: 1.0000 - val_loss: 0.1023
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9471 - loss: 0.1462 - val_accuracy: 1.0000 - val_loss: 0.1002
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9449 - loss: 0.1389 - val_accuracy: 1.0000 - val_loss: 0.0978
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9690 - loss: 0.1253 - val_accuracy: 1.0000 - val_loss: 0.0964
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9470 - loss: 0.1334 - val_accuracy: 1.0000 - val_loss: 0.0944
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9601 - loss: 0.1308 - val_accuracy: 1.0000 - val_loss: 0.0932
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9597 - loss: 0.1283 - val_accuracy: 1.0000 - val_loss: 0.0913
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9597 - loss: 0.1211 - val_accuracy: 1.0000 - val_loss: 0.0904
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9677 - loss: 0.1170 - val_accuracy: 1.0000 - val_loss: 0.0888
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9586 - loss: 0.1157 - val_accuracy: 1.0000 - val_loss: 0.0874
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9664 - loss: 0.1227 - val_accuracy: 1.0000 - val_loss: 0.0861
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9629 - loss: 0.1207 - val_accuracy: 1.0000 - val_loss: 0.0844
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9588 - loss: 0.1091 - val_accuracy: 1.0000 - val_loss: 0.0839
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9690 - loss: 0.1080 - val_accuracy: 1.0000 - val_loss: 0.0819
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9423 - loss: 0.1293 - val_accuracy: 1.0000 - val_loss: 0.0805
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9575 - loss: 0.1253 - val_accuracy: 1.0000 - val_loss: 0.0792
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9495 - loss: 0.1257 - val_accuracy: 1.0000 - val_loss: 0.0779
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9669 - loss: 0.1036 - val_accuracy: 1.0000 - val_loss: 0.0766
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9486 - loss: 0.1211 - val_accuracy: 1.0000 - val_loss: 0.0745
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9477 - loss: 0.1261 - val_accuracy: 1.0000 - val_loss: 0.0740
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9406 - loss: 0.1331 - val_accuracy: 1.0000 - val_loss: 0.0726
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9599 - loss: 0.1137 - val_accuracy: 1.0000 - val_loss: 0.0715
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9593 - loss: 0.1204 - val_accuracy: 1.0000 - val_loss: 0.0705
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9482 - loss: 0.1194 - val_accuracy: 1.0000 - val_loss: 0.0697
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9617 - loss: 0.1050 - val_accuracy: 1.0000 - val_loss: 0.0688
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9606 - loss: 0.1029 - val_accuracy: 1.0000 - val_loss: 0.0672
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9488 - loss: 0.1157 - val_accuracy: 1.0000 - val_loss: 0.0662
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9556 - loss: 0.1106 - val_accuracy: 1.0000 - val_loss: 0.0659
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9612 - loss: 0.1096 - val_accuracy: 1.0000 - val_loss: 0.0652
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9713 - loss: 0.1021 - val_accuracy: 1.0000 - val_loss: 0.0638
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9728 - loss: 0.1065 - val_accuracy: 1.0000 - val_loss: 0.0620
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9498 - loss: 0.1211 - val_accuracy: 1.0000 - val_loss: 0.0607
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9606 - loss: 0.0979 - val_accuracy: 1.0000 - val_loss: 0.0603
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9636 - loss: 0.1000 - val_accuracy: 1.0000 - val_loss: 0.0593
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9702 - loss: 0.1124 - val_accuracy: 1.0000 - val_loss: 0.0582
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9690 - loss: 0.0898 - val_accuracy: 1.0000 - val_loss: 0.0576
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9645 - loss: 0.0962 - val_accuracy: 1.0000 - val_loss: 0.0571
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9752 - loss: 0.0977 - val_accuracy: 1.0000 - val_loss: 0.0573
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9762 - loss: 0.0900 - val_accuracy: 1.0000 - val_loss: 0.0558
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9817 - loss: 0.0859 - val_accuracy: 1.0000 - val_loss: 0.0548
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9698 - loss: 0.0879 - val_accuracy: 1.0000 - val_loss: 0.0531
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9578 - loss: 0.1077 - val_accuracy: 1.0000 - val_loss: 0.0518
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9710 - loss: 0.0984 - val_accuracy: 1.0000 - val_loss: 0.0515
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9530 - loss: 0.1014 - val_accuracy: 1.0000 - val_loss: 0.0510
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9726 - loss: 0.0864 - val_accuracy: 1.0000 - val_loss: 0.0512
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9580 - loss: 0.1075 - val_accuracy: 1.0000 - val_loss: 0.0488
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9704 - loss: 0.0859 - val_accuracy: 1.0000 - val_loss: 0.0484
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9673 - loss: 0.0884 - val_accuracy: 1.0000 - val_loss: 0.0477
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9732 - loss: 0.0832 - val_accuracy: 1.0000 - val_loss: 0.0489
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9673 - loss: 0.0926 - val_accuracy: 1.0000 - val_loss: 0.0463
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9669 - loss: 0.0931 - val_accuracy: 1.0000 - val_loss: 0.0465
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9730 - loss: 0.0938 - val_accuracy: 1.0000 - val_loss: 0.0454
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9671 - loss: 0.0873 - val_accuracy: 1.0000 - val_loss: 0.0458
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9704 - loss: 0.0859 - val_accuracy: 1.0000 - val_loss: 0.0456
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9726 - loss: 0.0855 - val_accuracy: 1.0000 - val_loss: 0.0443
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9735 - loss: 0.0883 - val_accuracy: 1.0000 - val_loss: 0.0435
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9724 - loss: 0.0846 - val_accuracy: 1.0000 - val_loss: 0.0429
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9554 - loss: 0.0929 - val_accuracy: 1.0000 - val_loss: 0.0446
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9680 - loss: 0.0946 - val_accuracy: 1.0000 - val_loss: 0.0425
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9695 - loss: 0.0860 - val_accuracy: 1.0000 - val_loss: 0.0424
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9709 - loss: 0.0836 - val_accuracy: 1.0000 - val_loss: 0.0407
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9691 - loss: 0.0807 - val_accuracy: 1.0000 - val_loss: 0.0413
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9648 - loss: 0.0856 - val_accuracy: 1.0000 - val_loss: 0.0396
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9595 - loss: 0.0807 - val_accuracy: 1.0000 - val_loss: 0.0398
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9631 - loss: 0.0910 - val_accuracy: 1.0000 - val_loss: 0.0394
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9667 - loss: 0.0917 - val_accuracy: 1.0000 - val_loss: 0.0392
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9694 - loss: 0.0861 - val_accuracy: 1.0000 - val_loss: 0.0374
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9624 - loss: 0.0903 - val_accuracy: 1.0000 - val_loss: 0.0378
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9678 - loss: 0.0855 - val_accuracy: 1.0000 - val_loss: 0.0375
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9572 - loss: 0.0893 - val_accuracy: 1.0000 - val_loss: 0.0362
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9693 - loss: 0.0828 - val_accuracy: 1.0000 - val_loss: 0.0355
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9689 - loss: 0.0735 - val_accuracy: 1.0000 - val_loss: 0.0356
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9624 - loss: 0.0909 - val_accuracy: 1.0000 - val_loss: 0.0349
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9715 - loss: 0.0799 - val_accuracy: 1.0000 - val_loss: 0.0345
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9746 - loss: 0.0768 - val_accuracy: 1.0000 - val_loss: 0.0339
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9743 - loss: 0.0758 - val_accuracy: 1.0000 - val_loss: 0.0331
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9676 - loss: 0.0799 - val_accuracy: 1.0000 - val_loss: 0.0331
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9728 - loss: 0.0794 - val_accuracy: 1.0000 - val_loss: 0.0320
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9665 - loss: 0.0865 - val_accuracy: 1.0000 - val_loss: 0.0315
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9659 - loss: 0.0870 - val_accuracy: 1.0000 - val_loss: 0.0310
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9682 - loss: 0.0751 - val_accuracy: 1.0000 - val_loss: 0.0319
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9665 - loss: 0.0832 - val_accuracy: 1.0000 - val_loss: 0.0316
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9739 - loss: 0.0727 - val_accuracy: 1.0000 - val_loss: 0.0319
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9700 - loss: 0.0807 - val_accuracy: 1.0000 - val_loss: 0.0296
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9622 - loss: 0.0861 - val_accuracy: 1.0000 - val_loss: 0.0296
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9728 - loss: 0.0697 - val_accuracy: 1.0000 - val_loss: 0.0301
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9635 - loss: 0.0827 - val_accuracy: 1.0000 - val_loss: 0.0301
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9743 - loss: 0.0710 - val_accuracy: 1.0000 - val_loss: 0.0287
11/11 - 0s - 3ms/step - accuracy: 0.9760 - loss: 0.0707

In [53]:
model_logit_false= keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_false.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.9908 - loss: 0.0181 - val_accuracy: 1.0000 - val_loss: 9.5277e-04
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9895 - loss: 0.0217 - val_accuracy: 1.0000 - val_loss: 9.1483e-04
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9949 - loss: 0.0119 - val_accuracy: 1.0000 - val_loss: 9.3791e-04
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9921 - loss: 0.0182 - val_accuracy: 1.0000 - val_loss: 9.0165e-04
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9947 - loss: 0.0127 - val_accuracy: 1.0000 - val_loss: 8.8097e-04
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9971 - loss: 0.0115 - val_accuracy: 1.0000 - val_loss: 8.8866e-04
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9961 - loss: 0.0141 - val_accuracy: 1.0000 - val_loss: 8.8964e-04
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0114 - val_accuracy: 1.0000 - val_loss: 8.9550e-04
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0123 - val_accuracy: 1.0000 - val_loss: 9.2144e-04
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9949 - loss: 0.0141 - val_accuracy: 1.0000 - val_loss: 8.8267e-04
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9949 - loss: 0.0150 - val_accuracy: 1.0000 - val_loss: 8.8918e-04
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9908 - loss: 0.0217 - val_accuracy: 1.0000 - val_loss: 8.8891e-04
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0128 - val_accuracy: 1.0000 - val_loss: 9.0574e-04
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9989 - loss: 0.0093 - val_accuracy: 1.0000 - val_loss: 9.1640e-04
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9923 - loss: 0.0135 - val_accuracy: 1.0000 - val_loss: 9.4870e-04
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9917 - loss: 0.0179 - val_accuracy: 1.0000 - val_loss: 9.0027e-04
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9921 - loss: 0.0181 - val_accuracy: 1.0000 - val_loss: 8.6144e-04
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9908 - loss: 0.0146 - val_accuracy: 1.0000 - val_loss: 8.5050e-04
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0123 - val_accuracy: 1.0000 - val_loss: 8.4870e-04
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9917 - loss: 0.0148 - val_accuracy: 1.0000 - val_loss: 8.6665e-04
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9917 - loss: 0.0195 - val_accuracy: 1.0000 - val_loss: 8.2712e-04
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9963 - loss: 0.0109 - val_accuracy: 1.0000 - val_loss: 8.2112e-04
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9974 - loss: 0.0131 - val_accuracy: 1.0000 - val_loss: 8.2345e-04
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9974 - loss: 0.0135 - val_accuracy: 1.0000 - val_loss: 8.3831e-04
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9989 - loss: 0.0088 - val_accuracy: 1.0000 - val_loss: 8.5026e-04
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9934 - loss: 0.0128 - val_accuracy: 1.0000 - val_loss: 8.2169e-04
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9908 - loss: 0.0149 - val_accuracy: 1.0000 - val_loss: 8.1559e-04
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9989 - loss: 0.0111 - val_accuracy: 1.0000 - val_loss: 8.4843e-04
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9908 - loss: 0.0178 - val_accuracy: 1.0000 - val_loss: 8.2704e-04
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9895 - loss: 0.0175 - val_accuracy: 1.0000 - val_loss: 8.0893e-04
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9982 - loss: 0.0110 - val_accuracy: 1.0000 - val_loss: 8.0914e-04
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9982 - loss: 0.0117 - val_accuracy: 1.0000 - val_loss: 8.1176e-04
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9982 - loss: 0.0097 - val_accuracy: 1.0000 - val_loss: 7.9796e-04
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9943 - loss: 0.0133 - val_accuracy: 1.0000 - val_loss: 8.0094e-04
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9989 - loss: 0.0088 - val_accuracy: 1.0000 - val_loss: 8.0542e-04
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9895 - loss: 0.0191 - val_accuracy: 1.0000 - val_loss: 7.8678e-04
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9956 - loss: 0.0111 - val_accuracy: 1.0000 - val_loss: 7.9301e-04
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0133 - val_accuracy: 1.0000 - val_loss: 8.2625e-04
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9917 - loss: 0.0156 - val_accuracy: 1.0000 - val_loss: 8.0864e-04
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9917 - loss: 0.0166 - val_accuracy: 1.0000 - val_loss: 7.7869e-04
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9943 - loss: 0.0137 - val_accuracy: 1.0000 - val_loss: 7.7698e-04
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9895 - loss: 0.0201 - val_accuracy: 1.0000 - val_loss: 7.7218e-04
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9935 - loss: 0.0181 - val_accuracy: 1.0000 - val_loss: 7.8939e-04
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0113 - val_accuracy: 1.0000 - val_loss: 7.7426e-04
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9982 - loss: 0.0132 - val_accuracy: 1.0000 - val_loss: 7.7916e-04
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9934 - loss: 0.0140 - val_accuracy: 1.0000 - val_loss: 7.7014e-04
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9895 - loss: 0.0188 - val_accuracy: 1.0000 - val_loss: 7.5840e-04
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9935 - loss: 0.0212 - val_accuracy: 1.0000 - val_loss: 7.5484e-04
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9869 - loss: 0.0207 - val_accuracy: 1.0000 - val_loss: 7.4796e-04
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9895 - loss: 0.0203 - val_accuracy: 1.0000 - val_loss: 7.5001e-04
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9934 - loss: 0.0156 - val_accuracy: 1.0000 - val_loss: 7.5595e-04
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0116 - val_accuracy: 1.0000 - val_loss: 7.6631e-04
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9943 - loss: 0.0146 - val_accuracy: 1.0000 - val_loss: 7.6138e-04
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9982 - loss: 0.0108 - val_accuracy: 1.0000 - val_loss: 7.6287e-04
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9869 - loss: 0.0202 - val_accuracy: 1.0000 - val_loss: 7.5267e-04
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9989 - loss: 0.0074 - val_accuracy: 1.0000 - val_loss: 7.8053e-04
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9934 - loss: 0.0146 - val_accuracy: 1.0000 - val_loss: 7.3580e-04
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9982 - loss: 0.0107 - val_accuracy: 1.0000 - val_loss: 7.3940e-04
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9989 - loss: 0.0079 - val_accuracy: 1.0000 - val_loss: 7.7228e-04
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9943 - loss: 0.0127 - val_accuracy: 1.0000 - val_loss: 7.2627e-04
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9917 - loss: 0.0174 - val_accuracy: 1.0000 - val_loss: 7.2616e-04
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0090 - val_accuracy: 1.0000 - val_loss: 7.1834e-04
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0097 - val_accuracy: 1.0000 - val_loss: 7.1937e-04
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9908 - loss: 0.0176 - val_accuracy: 1.0000 - val_loss: 7.1355e-04
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9908 - loss: 0.0176 - val_accuracy: 1.0000 - val_loss: 7.1376e-04
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9956 - loss: 0.0098 - val_accuracy: 1.0000 - val_loss: 7.1365e-04
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9989 - loss: 0.0091 - val_accuracy: 1.0000 - val_loss: 7.2984e-04
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9908 - loss: 0.0145 - val_accuracy: 1.0000 - val_loss: 7.1538e-04
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9917 - loss: 0.0136 - val_accuracy: 1.0000 - val_loss: 7.1457e-04
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9895 - loss: 0.0206 - val_accuracy: 1.0000 - val_loss: 7.0253e-04
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9943 - loss: 0.0108 - val_accuracy: 1.0000 - val_loss: 6.9578e-04
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9989 - loss: 0.0111 - val_accuracy: 1.0000 - val_loss: 7.2193e-04
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9921 - loss: 0.0137 - val_accuracy: 1.0000 - val_loss: 6.8927e-04
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9989 - loss: 0.0127 - val_accuracy: 1.0000 - val_loss: 7.1912e-04
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9943 - loss: 0.0113 - val_accuracy: 1.0000 - val_loss: 6.8141e-04
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9921 - loss: 0.0129 - val_accuracy: 1.0000 - val_loss: 6.7155e-04
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9982 - loss: 0.0095 - val_accuracy: 1.0000 - val_loss: 6.7602e-04
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9923 - loss: 0.0114 - val_accuracy: 1.0000 - val_loss: 7.1391e-04
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9971 - loss: 0.0082 - val_accuracy: 1.0000 - val_loss: 6.9465e-04
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9947 - loss: 0.0123 - val_accuracy: 1.0000 - val_loss: 6.6865e-04
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9895 - loss: 0.0187 - val_accuracy: 1.0000 - val_loss: 6.6467e-04
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9956 - loss: 0.0127 - val_accuracy: 1.0000 - val_loss: 6.6078e-04
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9934 - loss: 0.0151 - val_accuracy: 1.0000 - val_loss: 6.5760e-04
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9943 - loss: 0.0137 - val_accuracy: 1.0000 - val_loss: 6.5884e-04
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9982 - loss: 0.0096 - val_accuracy: 1.0000 - val_loss: 6.6292e-04
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9956 - loss: 0.0101 - val_accuracy: 1.0000 - val_loss: 6.6385e-04
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9982 - loss: 0.0097 - val_accuracy: 1.0000 - val_loss: 6.6833e-04
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9943 - loss: 0.0140 - val_accuracy: 1.0000 - val_loss: 6.4941e-04
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9974 - loss: 0.0140 - val_accuracy: 1.0000 - val_loss: 6.5375e-04
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9961 - loss: 0.0167 - val_accuracy: 1.0000 - val_loss: 6.4883e-04
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9982 - loss: 0.0085 - val_accuracy: 1.0000 - val_loss: 6.5556e-04
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9869 - loss: 0.0188 - val_accuracy: 1.0000 - val_loss: 6.3903e-04
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9961 - loss: 0.0148 - val_accuracy: 1.0000 - val_loss: 6.3699e-04
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9949 - loss: 0.0110 - val_accuracy: 1.0000 - val_loss: 6.2597e-04
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9989 - loss: 0.0072 - val_accuracy: 1.0000 - val_loss: 6.3099e-04
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9943 - loss: 0.0114 - val_accuracy: 1.0000 - val_loss: 6.2197e-04
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9961 - loss: 0.0135 - val_accuracy: 1.0000 - val_loss: 6.2114e-04
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9943 - loss: 0.0106 - val_accuracy: 1.0000 - val_loss: 6.1381e-04
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9974 - loss: 0.0127 - val_accuracy: 1.0000 - val_loss: 6.1476e-04
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9974 - loss: 0.0123 - val_accuracy: 1.0000 - val_loss: 6.1215e-04
11/11 - 0s - 2ms/step - accuracy: 0.9970 - loss: 0.0103

In [50]:
model_logit_false.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

array([[9.88142490e-01, 1.18573923e-02, 8.89537402e-12],
       [2.61107719e-10, 9.98682439e-01, 1.31759525e-03],
       [9.99100149e-01, 8.99873383e-04, 1.68197817e-10],
       [3.08774983e-18, 1.30799599e-04, 9.99869227e-01],
       [9.98640358e-01, 1.35963189e-03, 8.15793766e-10],
       [1.93247997e-05, 9.99910176e-01, 7.05471684e-05],
       [1.68098528e-02, 9.83189106e-01, 1.03515595e-06],
       [8.63155120e-12, 2.66610202e-03, 9.97333825e-01],
       [6.09443390e-14, 9.75598115e-04, 9.99024391e-01],
       [6.14953585e-15, 1.67995936e-03, 9.98320043e-01],
       [9.73193586e-01, 2.68053468e-02, 1.01961007e-06],
       [9.98983324e-01, 1.01666572e-03, 2.68261940e-10],
       [1.73615560e-01, 8.26384425e-01, 1.55475792e-08],
       [9.99893129e-01, 1.06891341e-04, 3.39110420e-14],
       [3.66144086e-05, 9.99961913e-01, 1.57054490e-06],
       [9.99512792e-01, 4.87227429e-04, 5.81982704e-13],
       [9.99863744e-01, 1.36190007e-04, 3.00401726e-14],
       [1.04101466e-18, 1.04869679e-04, 9.99895155e-01],
       [9.99912560e-01, 8.74724719e-05, 2.26454106e-14],
       [6.35993911e-06, 9.99977529e-01, 1.62419110e-05],
       [9.98709798e-01, 1.29024172e-03, 6.67614908e-10],
       [9.98349071e-01, 1.65094121e-03, 1.71489378e-09],
       [1.21181176e-09, 9.96891618e-01, 3.10833449e-03],
       [3.65118598e-18, 1.35331225e-04, 9.99864697e-01],
       [9.99652326e-01, 3.47791356e-04, 6.65095149e-14],
       [9.99371946e-01, 6.28105190e-04, 9.44739146e-14],
       [1.47564575e-18, 1.12575173e-04, 9.99887466e-01],
       [3.34785233e-04, 9.99558091e-01, 1.07175780e-04],
       [1.68086510e-15, 4.70456784e-04, 9.99529541e-01],
       [9.46633145e-02, 9.05333221e-01, 3.46842171e-06],
       [2.62522096e-17, 2.38310953e-04, 9.99761581e-01],
       [2.39414544e-06, 9.99977767e-01, 1.98702746e-05],
       [9.98722672e-01, 1.27740821e-03, 6.42560671e-10],
       [9.99580979e-01, 4.18957585e-04, 2.26863363e-12],
       [2.44192506e-07, 9.86404657e-01, 1.35950763e-02],
       [1.09893235e-03, 9.98886108e-01, 1.49273601e-05],
       [2.02352501e-04, 1.99909285e-01, 7.99888253e-01],
       [9.15007665e-22, 2.50947032e-05, 9.99974906e-01],
       [9.99892116e-01, 1.07867243e-04, 5.04600329e-14],
       [9.99670565e-01, 3.29401926e-04, 3.22328834e-13],
       [9.99970138e-01, 2.99140229e-05, 3.74544893e-16],
       [9.99898374e-01, 1.01674726e-04, 4.02516020e-14],
       [2.40418064e-13, 1.28913182e-03, 9.98710871e-01],
       [2.13898469e-14, 7.88713049e-04, 9.99211311e-01],
       [9.99409139e-01, 5.90757409e-04, 3.36312332e-11],
       [9.99128640e-01, 8.71392665e-04, 5.89800344e-12],
       [1.13506301e-03, 9.98856008e-01, 8.80414791e-06],
       [9.98745620e-01, 1.25442131e-03, 5.99429562e-10],
       [9.99299347e-01, 7.00748584e-04, 6.46173184e-11],
       [7.74924364e-03, 9.92003918e-01, 2.46917130e-04],
       [9.99811530e-01, 1.88435617e-04, 4.25799587e-13],
       [1.25895103e-13, 1.13045145e-03, 9.98869479e-01],
       [4.24952071e-19, 8.74126054e-05, 9.99912679e-01],
       [9.99232233e-01, 7.67693156e-04, 9.16031695e-11],
       [9.99958456e-01, 4.16296425e-05, 1.32493179e-15],
       [4.21744778e-10, 5.86170005e-03, 9.94138360e-01],
       [9.76532042e-01, 2.34679505e-02, 8.35262588e-12],
       [9.99393702e-01, 6.06340356e-04, 3.71524617e-11],
       [3.07694544e-14, 8.49163975e-04, 9.99150872e-01],
       [7.47393469e-21, 3.84550840e-05, 9.99961555e-01],
       [2.01680921e-02, 9.79831755e-01, 1.36431041e-07],
       [4.06903855e-05, 9.99714196e-01, 2.45137839e-04],
       [2.42111948e-03, 9.97554898e-01, 2.38788580e-05],
       [9.99943137e-01, 5.68745490e-05, 4.36776393e-15],
       [9.98507917e-01, 1.49202289e-03, 1.16414911e-09],
       [1.20482797e-08, 9.99973834e-01, 2.61738387e-05],
       [9.98800099e-01, 1.19993067e-03, 1.38518736e-11],
       [1.01051720e-20, 4.08860433e-05, 9.99959171e-01],
       [9.99783456e-01, 2.16546323e-04, 7.63604810e-14],
       [5.15581489e-01, 4.84418482e-01, 7.41800132e-09],
       [9.99917209e-01, 8.27960175e-05, 1.83549261e-14],
       [9.99247372e-01, 7.52577558e-04, 8.48937656e-11],
       [1.05845318e-18, 1.05224281e-04, 9.99894798e-01],
       [4.14005081e-05, 9.99712050e-01, 2.46526615e-04],
       [4.55134477e-15, 5.75975922e-04, 9.99424040e-01],
       [6.19488187e-16, 3.84102226e-04, 9.99615967e-01],
       [9.99020696e-01, 9.79308737e-04, 2.32466463e-10],
       [9.99320626e-01, 6.79445220e-04, 5.74204642e-11],
       [9.98519003e-01, 1.48097344e-03, 1.13149756e-09],
       [2.86970588e-13, 1.33630028e-03, 9.98663664e-01],
       [9.78342235e-01, 2.16577370e-02, 1.78262249e-11],
       [9.98473167e-01, 1.52692315e-03, 1.27185396e-09],
       [5.14532861e-13, 2.59455317e-03, 9.97405529e-01],
       [9.99841392e-01, 1.58622453e-04, 5.54849102e-14],
       [1.48637655e-05, 9.99933839e-01, 5.12427650e-05],
       [7.60963754e-21, 3.85959429e-05, 9.99961436e-01],
       [9.99299586e-01, 7.00460456e-04, 6.45157261e-11],
       [3.89252452e-09, 9.90221739e-01, 9.77826957e-03],
       [1.88528047e-11, 4.05104235e-02, 9.59489524e-01],
       [2.80086082e-16, 3.26891080e-04, 9.99673069e-01],
       [1.69328990e-18, 1.15766910e-04, 9.99884248e-01],
       [1.94438486e-04, 9.99654949e-01, 1.50667387e-04],
       [9.98619735e-01, 1.38036860e-03, 8.64442018e-10],
       [9.98698294e-01, 1.30174705e-03, 6.90683288e-10],
       [9.98836756e-01, 1.16325950e-03, 4.49123128e-10],
       [9.99953747e-01, 4.62054086e-05, 1.41335441e-15],
       [9.98403549e-01, 1.59641763e-03, 1.50804791e-09],
       [1.39349940e-17, 1.77664479e-04, 9.99822259e-01],
       [9.98930275e-01, 1.06971571e-03, 3.25889205e-10],
       [9.99412477e-01, 5.87509072e-04, 3.29294335e-11],
       [9.97671247e-01, 2.32885941e-03, 3.03126068e-13],
       [2.87864037e-04, 9.99028206e-01, 6.84009632e-04],
       [5.80073947e-06, 9.97512579e-01, 2.48159771e-03],
       [9.99521255e-01, 4.78721457e-04, 6.01182732e-13],
       [3.54675816e-12, 2.22601416e-03, 9.97774005e-01],
       [9.99887943e-01, 1.12071975e-04, 5.84035993e-14],
       [5.87593125e-18, 1.49070285e-04, 9.99850929e-01],
       [1.57529121e-14, 7.41201453e-04, 9.99258876e-01],
       [9.99931812e-01, 6.81285092e-05, 8.71006097e-15],
       [2.93663219e-11, 3.41734407e-03, 9.96582627e-01],
       [9.99748588e-01, 2.51506281e-04, 4.76698047e-14],
       [5.86959004e-06, 9.91258919e-01, 8.73512402e-03],
       [9.25777793e-01, 7.42221996e-02, 4.14872261e-08],
       [7.15250290e-11, 4.09285817e-03, 9.95907187e-01],
       [1.35476575e-17, 1.76649439e-04, 9.99823332e-01],
       [1.10725917e-17, 1.69554245e-04, 9.99830365e-01],
       [9.99703407e-01, 2.96633400e-04, 6.35693212e-14],
       [7.77654331e-17, 2.51957244e-04, 9.99748111e-01],
       [9.46100056e-01, 5.38999848e-02, 1.92102623e-09],
       [3.28866762e-13, 1.37378625e-03, 9.98626173e-01],
       [9.98596191e-01, 1.40382804e-03, 9.22025567e-10],
       [1.97272322e-15, 4.86010977e-04, 9.99513984e-01],
       [1.13550603e-04, 9.99848783e-01, 3.76806202e-05],
       [9.99193072e-01, 8.06868251e-04, 1.10812241e-10],
       [9.98496592e-01, 1.50334660e-03, 1.19832522e-09],
       [7.76477904e-09, 9.89796698e-01, 1.02033755e-02],
       [9.99896109e-01, 1.03950631e-04, 4.38064231e-14],
       [9.99599874e-01, 4.00184392e-04, 7.58379904e-12],
       [9.98662114e-01, 1.33790111e-03, 7.67015729e-10],
       [2.79035679e-20, 5.02600087e-05, 9.99949694e-01],
       [9.97962236e-01, 2.03773170e-03, 1.93953360e-12],
       [9.99052346e-01, 9.47675086e-04, 2.05025594e-10],
       [6.90221579e-16, 3.92633112e-04, 9.99607384e-01],
       [9.99808669e-01, 1.91342813e-04, 4.51467965e-13],
       [9.99968946e-01, 3.11372642e-05, 3.22269620e-16],
       [9.99955237e-01, 4.47739767e-05, 1.75019580e-15],
       [3.34266465e-17, 2.12234343e-04, 9.99787748e-01],
       [9.24222410e-01, 7.57774487e-02, 1.22887187e-07],
       [5.86467236e-03, 9.94125605e-01, 9.74645900e-06],
       [9.99741077e-01, 2.58936954e-04, 6.42503628e-13],
       [9.99450445e-01, 5.49655291e-04, 2.55250283e-11],
       [2.61872729e-15, 5.14800835e-04, 9.99485195e-01],
       [9.99883533e-01, 1.16508570e-04, 6.77485412e-14],
       [7.27852566e-17, 9.17680681e-01, 8.23193416e-02],
       [3.82724849e-16, 3.48299829e-04, 9.99651730e-01],
       [1.15579937e-03, 9.98844028e-01, 6.17303968e-08],
       [1.32793193e-20, 4.32200941e-05, 9.99956787e-01],
       [5.71409142e-09, 9.99897897e-01, 1.02204998e-04],
       [8.19190604e-16, 4.06538631e-04, 9.99593437e-01],
       [2.55821122e-17, 2.01007235e-04, 9.99798954e-01],
       [9.20885438e-13, 1.69313909e-03, 9.98306930e-01],
       [2.30016689e-13, 1.27760891e-03, 9.98722434e-01],
       [9.98483539e-01, 1.51639408e-03, 1.23861865e-09],
       [9.99133348e-01, 8.66637623e-04, 1.45646800e-10],
       [1.02665835e-13, 1.08458754e-03, 9.98915434e-01],
       [1.44140862e-11, 2.27649510e-02, 9.77234960e-01],
       [4.10172486e-14, 9.00216342e-04, 9.99099791e-01],
       [9.99791443e-01, 2.08599886e-04, 1.95410393e-13],
       [2.93727043e-10, 5.44801075e-03, 9.94551957e-01],
       [1.33577585e-08, 1.17747560e-02, 9.88225162e-01],
       [9.98716474e-01, 1.28359045e-03, 6.54540422e-10],
       [1.97344972e-03, 9.97999132e-01, 2.74120430e-05],
       [1.43708767e-05, 9.99979794e-01, 5.84411328e-06],
       [1.15263094e-04, 9.98429835e-01, 1.45486742e-03],
       [3.50262120e-17, 2.14259431e-04, 9.99785721e-01],
       [6.21259932e-09, 1.00918962e-02, 9.89908099e-01],
       [1.44146861e-18, 1.12040449e-04, 9.99887943e-01],
       [3.92899240e-15, 5.59025910e-04, 9.99441028e-01],
       [2.36930997e-18, 1.23945996e-04, 9.99876022e-01],
       [9.95490730e-01, 4.50926367e-03, 3.56114834e-12],
       [9.99307930e-01, 6.92099333e-04, 6.16195359e-11],
       [7.77296775e-20, 6.18934209e-05, 9.99938130e-01],
       [3.69205259e-06, 9.98995245e-01, 1.00107945e-03],
       [9.99451876e-01, 5.48165932e-04, 1.87857650e-13],
       [1.51444428e-05, 9.99973953e-01, 1.09804860e-05],
       [2.54484075e-05, 9.99973238e-01, 1.42870908e-06],
       [9.97378349e-01, 2.62169284e-03, 1.00748485e-08],
       [9.99899566e-01, 1.00478224e-04, 3.84704950e-14],
       [9.99355018e-01, 6.44960441e-04, 1.72393610e-12],
       [9.99839127e-01, 1.60943571e-04, 2.55445604e-14],
       [1.89736556e-06, 9.99988437e-01, 9.60268517e-06],
       [9.98997152e-01, 1.00284908e-03, 2.54580024e-10],
       [3.26194611e-15, 8.42117821e-04, 9.99157906e-01],
       [7.81083600e-06, 9.99981582e-01, 1.06197785e-05],
       [9.97920752e-01, 2.07923446e-03, 4.14667500e-09],
       [1.63800809e-12, 1.90305465e-03, 9.98096943e-01],
       [1.29049972e-19, 6.86102503e-05, 9.99931335e-01],
       [9.98741925e-01, 1.25808991e-03, 4.78653358e-13],
       [2.00810595e-04, 9.99764323e-01, 3.48187932e-05],
       [9.98812616e-01, 1.18734315e-03, 4.85754381e-10],
       [3.36679723e-03, 9.96606290e-01, 2.68267468e-05],
       [9.97007966e-01, 2.99196085e-03, 1.67117769e-08],
       [4.32540627e-14, 9.09977243e-04, 9.99090075e-01],
       [1.92430332e-01, 8.07569325e-01, 2.73790363e-07],
       [8.65427962e-15, 6.56293065e-04, 9.99343693e-01],
       [9.99268055e-01, 7.31982465e-04, 7.63457006e-11],
       [9.99948144e-01, 5.18226225e-05, 2.75616771e-15],
       [9.99233425e-01, 7.66464742e-04, 9.10436171e-11],
       [1.29708601e-15, 4.46324673e-04, 9.99553621e-01],
       [9.99782503e-01, 2.17530745e-04, 2.67701903e-13],
       [1.09430825e-19, 6.63489773e-05, 9.99933600e-01],
       [9.99222100e-01, 7.77894398e-04, 9.63470276e-11],
       [2.06785090e-02, 9.79321420e-01, 1.32105455e-08],
       [9.99072671e-01, 9.27326677e-04, 1.88688912e-10],
       [9.98072624e-01, 1.92733994e-03, 3.10149373e-09],
       [6.22306424e-15, 6.13767246e-04, 9.99386191e-01],
       [5.40300547e-25, 5.53837663e-06, 9.99994516e-01],
       [6.68041333e-16, 3.90036264e-04, 9.99610007e-01],
       [8.87031555e-01, 1.12964951e-01, 3.45769308e-06],
       [9.99534667e-01, 4.65302437e-04, 1.34978834e-11],
       [9.97574806e-01, 2.42508249e-03, 7.47438200e-09],
       [1.18256493e-19, 6.74031398e-05, 9.99932647e-01],
       [1.09105936e-11, 2.79584411e-03, 9.97204185e-01],
       [9.99791443e-01, 2.08559693e-04, 6.27609781e-13],
       [9.98776317e-01, 1.22367719e-03, 5.45134604e-10],
       [8.17951289e-08, 9.99759436e-01, 2.40429101e-04],
       [9.99942183e-01, 5.78659710e-05, 4.66605082e-15],
       [2.60097961e-20, 4.95473214e-05, 9.99950409e-01],
       [9.99207139e-01, 7.92865874e-04, 1.03634962e-10],
       [5.96522645e-04, 9.99358594e-01, 4.48596365e-05],
       [2.50013371e-04, 9.99604046e-01, 1.45995436e-04],
       [1.14709633e-06, 9.99996424e-01, 2.36184428e-06],
       [9.78041053e-01, 2.19589584e-02, 2.00303418e-09],
       [3.58845508e-15, 5.48824144e-04, 9.99451280e-01],
       [1.06391627e-02, 9.89360869e-01, 3.51930218e-08],
       [7.03319977e-17, 2.46865675e-04, 9.99753237e-01],
       [1.11581371e-16, 2.71137047e-04, 9.99728858e-01],
       [9.97858167e-01, 2.14191200e-03, 4.64604977e-09],
       [1.46261850e-10, 4.73091239e-03, 9.95269120e-01],
       [9.99902785e-01, 9.73165006e-05, 2.89471667e-15],
       [9.98782039e-01, 1.21787889e-03, 5.35317235e-10],
       [1.63205699e-11, 1.57180149e-02, 9.84282017e-01],
       [9.99097228e-01, 9.02772183e-04, 1.70279985e-10],
       [1.08732135e-13, 1.09730486e-03, 9.98902678e-01],
       [9.99093771e-01, 9.06206493e-04, 1.72771325e-10],
       [3.80566990e-15, 5.55416162e-04, 9.99444604e-01],
       [2.56412946e-10, 9.95004237e-01, 4.99579776e-03],
       [9.99820590e-01, 1.79352079e-04, 2.81671811e-14],
       [2.63833664e-02, 9.73616481e-01, 2.41745425e-07],
       [4.65538363e-09, 9.52145178e-03, 9.90478516e-01],
       [2.50835874e-05, 9.98972654e-01, 1.00226526e-03],
       [9.99360144e-01, 6.39810925e-04, 1.07781914e-13],
       [2.29596242e-15, 5.01226343e-04, 9.99498725e-01],
       [3.21034364e-14, 8.56515020e-04, 9.99143481e-01],
       [9.86234130e-16, 4.22159443e-04, 9.99577880e-01],
       [9.99583840e-01, 4.16092866e-04, 8.80292627e-12],
       [9.98286366e-01, 1.71372050e-03, 7.98420900e-13],
       [9.85148966e-01, 1.48510877e-02, 2.18949034e-12],
       [5.51810597e-10, 3.36118005e-02, 9.66388166e-01],
       [3.98357779e-12, 9.12331790e-03, 9.90876675e-01],
       [5.74264410e-16, 3.78232042e-04, 9.99621749e-01],
       [2.53374130e-01, 7.46625841e-01, 1.03549427e-08],
       [1.82174536e-19, 8.70535732e-05, 9.99913037e-01],
       [9.99422014e-01, 5.77898580e-04, 2.81838002e-13],
       [9.99699831e-01, 3.00193060e-04, 1.77429753e-13],
       [3.07244813e-10, 5.49784303e-03, 9.94502187e-01],
       [9.98837113e-01, 1.16283516e-03, 4.48496656e-10],
       [9.99726593e-01, 2.73405050e-04, 8.41132719e-14],
       [9.99603570e-01, 3.96455987e-04, 7.30393003e-12],
       [9.99920309e-01, 7.97731409e-05, 1.59221628e-14],
       [9.99706984e-01, 2.93030986e-04, 2.30332723e-12],
       [3.72871569e-12, 2.24872329e-03, 9.97751355e-01],
       [9.98195589e-01, 1.80442340e-03, 2.40997222e-09],
       [2.35359676e-05, 9.99973953e-01, 2.66553661e-06],
       [3.12857586e-03, 9.96871352e-01, 6.74088430e-09],
       [1.68281014e-12, 1.91350444e-03, 9.98086512e-01],
       [1.03084285e-05, 9.99508977e-01, 4.80605959e-04],
       [1.94742642e-16, 3.03622568e-04, 9.99696374e-01],
       [1.75085482e-17, 1.86100282e-04, 9.99813914e-01],
       [7.81719423e-15, 6.42870553e-04, 9.99357164e-01],
       [8.50780339e-07, 9.94409025e-01, 5.59008447e-03],
       [9.62624416e-14, 1.99238141e-03, 9.98007536e-01],
       [6.53655231e-02, 9.34634507e-01, 7.20086435e-09],
       [2.21605580e-02, 9.77809548e-01, 2.99936892e-05],
       [3.21807092e-05, 9.99924183e-01, 4.35813781e-05],
       [8.73834086e-14, 3.72107420e-03, 9.96279001e-01],
       [4.40752273e-14, 9.13459284e-04, 9.99086499e-01],
       [9.99603689e-01, 3.96391930e-04, 7.31262967e-12],
       [9.65412254e-18, 1.64896192e-04, 9.99835193e-01],
       [1.91795131e-15, 4.83238575e-04, 9.99516726e-01],
       [4.17175680e-13, 1.44174846e-03, 9.98558223e-01],
       [9.99014139e-01, 9.85885737e-04, 7.92494056e-11],
       [9.98973489e-01, 1.02650491e-03, 2.78330081e-10],
       [9.91886199e-01, 8.11377913e-03, 3.86736337e-11],
       [9.99174535e-01, 8.25440336e-04, 1.20890270e-10],
       [9.99099672e-01, 9.00331768e-04, 1.68525929e-10],
       [5.38870767e-16, 9.16023448e-04, 9.99083996e-01],
       [9.98575866e-01, 1.42421667e-03, 9.74331282e-10],
       [6.36963271e-16, 3.86279338e-04, 9.99613702e-01],
       [9.98183548e-01, 1.81646517e-03, 2.47211940e-09],
       [9.99769449e-01, 2.30479462e-04, 3.68941633e-14],
       [1.33178394e-13, 1.14343478e-03, 9.98856485e-01],
       [1.50761639e-18, 1.13066708e-04, 9.99886870e-01],
       [9.99940395e-01, 5.95693600e-05, 5.21337471e-15],
       [9.99869823e-01, 1.30137749e-04, 3.97033684e-14],
       [4.47119732e-04, 9.99550402e-01, 2.45583396e-06],
       [2.89937095e-17, 2.06186232e-04, 9.99793828e-01],
       [2.86961540e-06, 9.99931216e-01, 6.59719517e-05],
       [8.83075178e-01, 1.16924897e-01, 2.24782548e-09],
       [3.63911590e-06, 9.99749780e-01, 2.46626209e-04],
       [7.05730318e-15, 6.29653921e-04, 9.99370396e-01],
       [9.99866009e-01, 1.33933572e-04, 3.94812729e-14],
       [9.99091625e-01, 9.08359827e-04, 5.39934362e-13],
       [2.67514308e-15, 5.17034438e-04, 9.99483049e-01],
       [4.03104758e-15, 5.61946188e-04, 9.99438047e-01],
       [2.64442169e-05, 9.97419715e-01, 2.55389954e-03],
       [4.70268755e-17, 2.27478478e-04, 9.99772489e-01],
       [1.51305746e-09, 7.58888898e-03, 9.92411077e-01],
       [9.99848306e-01, 1.51734406e-04, 1.60291837e-14],
       [9.99948859e-01, 5.11816506e-05, 2.91845625e-15],
       [1.67408280e-15, 4.70070372e-04, 9.99529898e-01],
       [5.84543048e-13, 1.54393178e-03, 9.98456180e-01],
       [9.99353945e-01, 6.46021625e-04, 4.73454817e-11],
       [1.26390682e-14, 4.56725387e-03, 9.95432734e-01],
       [1.78732257e-03, 9.98208940e-01, 3.65036976e-06],
       [2.32653401e-16, 6.13153912e-04, 9.99386787e-01],
       [1.99354890e-05, 9.99975622e-01, 4.51450660e-06],
       [6.80728161e-18, 1.53594476e-04, 9.99846399e-01],
       [6.29578471e-06, 9.99963343e-01, 3.04565219e-05],
       [1.52959497e-15, 4.61528660e-04, 9.99538481e-01],
       [9.99893129e-01, 1.06860964e-04, 2.98666867e-14],
       [7.62473479e-19, 9.84392827e-05, 9.99901593e-01],
       [9.99367893e-01, 6.32083917e-04, 4.35562905e-11],
       [9.98057187e-01, 1.94282457e-03, 3.19797411e-09],
       [1.69546166e-18, 1.15797164e-04, 9.99884248e-01],
       [9.98330534e-01, 1.66942889e-03, 1.78956960e-09],
       [1.61706186e-08, 9.99875188e-01, 1.24800601e-04],
       [9.99912202e-01, 8.78718492e-05, 2.30432061e-14],
       [1.13546893e-14, 6.93514594e-04, 9.99306500e-01],
       [9.99169767e-01, 8.30192526e-04, 1.23574193e-10],
       [9.97942150e-01, 2.05781707e-03, 1.04883040e-12],
       [4.89814483e-05, 9.99921262e-01, 2.98592913e-05],
       [9.99606073e-01, 3.93928058e-04, 6.86030551e-14]], dtype=float32)

In [12]:
penguins['species']

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...
339    Chinstrap
340    Chinstrap
341    Chinstrap
342    Chinstrap
343    Chinstrap
Name: species, Length: 344, dtype: object

In [13]:
penguins_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)